# -*- mode: yaml; tab-width: 4; indent-tabs-mode: nil -*-
#
# Copyright (C) 2015 Marco Craveiro <marco.craveiro@gmail.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
# MA 02110-1301, USA.
#
language: cpp

compiler:
  # - clang # disabled due to gcc STL
  - gcc

before_install:
  # debian testing
  - sudo add-apt-repository "http://ftp.us.debian.org/debian testing main contrib non-free"
  - sudo apt-get update -qq
  - sudo apt-get install -qq qtbase5-dev libvtk6-dev libvtk6-qt-dev 

  # ninja
  - sudo apt-get install ninja-build

  # g++4.9
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.9; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9" GCOV="gcov-4.9"; fi

  # conan
  - wget https://s3-eu-west-1.amazonaws.com/conanio-production/downloads/conan-ubuntu-64_0_5_0.deb -O conan.deb
  - sudo dpkg -i conan.deb
  - rm conan.deb

  # cmake
  - wget --no-check-certificate https://cmake.org/files/v3.4/cmake-3.4.1-Linux-x86_64.tar.gz -O /tmp/cmake-3.4.1-Linux-x86_64.tar.gz
  - tar xf /tmp/cmake-3.4.1-Linux-x86_64.tar.gz -C /tmp
  - sudo cp -r /tmp/cmake-3.4.1-Linux-x86_64/* /usr

  # clang 3.4
  - if [ "$CXX" == "clang++" ]; then sudo apt-get install --allow-unauthenticated -qq clang-3.4; fi
  - if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.4" CC="clang-3.4"; fi

  # coverage
  - sudo pip install cpp-coveralls

install:
  # boost. install all for now.
  - sudo apt-get install libboost1.55-all-dev 

  # ninja
  - sudo apt-get install ninja-build

  # cmake
  - sudo apt-get install cmake

  # g++4.9
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.9; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9" GCOV="gcov-4.9"; fi

  # clang 3.4
  - if [ "$CXX" == "clang++" ]; then sudo apt-get install --allow-unauthenticated -qq clang-3.4; fi
  - if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.4" CC="clang-3.4"; fi

  # wt
  # - sudo apt-get install libwt-dev libwtext-dev

  # coverage
  - sudo pip install cpp-coveralls

script:
  - export GIT_REPO="`pwd`"
  - cd ${GIT_REPO}/build
  - mkdir output
  - cd output
  - conan install ${GIT_REPO}
  - cmake ${GIT_REPO} -DWITH_MINIMAL_PACKAGING=on
  - make -j2 run_all_specs

notifications:
  email:
    recipients:
      - marco.craveiro@gmail.com
    on_success: change
    on_failure: always

  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f65b7ca790d29439491d
    on_success: always
    on_failure: always

deploy:
  provider: releases
  api_key:
    secure: UdotUzhLJ7GcmwyJlpqcsvWsXxuWjoswXG7intkgxKeD5vkIT6Ng2v7ik6c/4uO9wXJ9uWV8/X/EzdZhWqFjiamMljsmFGcy4Bt37oqP6oxdlRyO/KrLM1E/xtmA1kZppuY4njCqzZnMslyzyMtsl+DH3zseOL7GQIbkL5xbecI=
  file_glob: true
  file: stage/pkg/*.deb
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
