#+title: Nerd Food: Neurons for Computer Geeks - Part III: More Electricity And Morphology
#+options: date:nil toc:nil author:nil num:nil title:nil

[[http://mcraveiro.blogspot.co.uk/2015/08/nerd-food-neurons-for-computer-geeks.html][Part I]] of this series looked at a neuron from above; [[http://mcraveiro.blogspot.co.uk/2015/08/nerd-food-neurons-for-computer-geeks_31.html][Part II]] attempted
to give us the fundamental building blocks in electricity required to
get us on the road to modeling neurons. Regrettably, part III is
somewhat more of the same as part II: now that we grok the basics of
electricity, we need to turn our attention to the /RC circuit/. As we
shall see, this circuit is of particular interest when modeling
neurons.

The RC circuit is so called because it is composed of a resistor and a
capacitor. We got some vague understanding of resistors, so lets have
a look at this crazy critter, /the capacitor/.

* Capacitors and Capacitance

Just like the battery is a source of current, one can think of the
capacitor as a temporary store of current: if you plug a capacitor
into a circuit with just a battery, it will start to "accumulate"
charge over time, up to a "maximum limit". But how exactly does this
process work?

[[https://www.khanacademy.org/science/physics/circuits-topic/circuits-with-capacitors/v/capacitors-and-capacitance][In simple terms]], the capacitor is made up of two metal plates, one of
which will connect to the positive end of the battery and another
which connects to the negative end. At the positive end, the metal
plate will start to lose negative charges because these are attracted
to the positive end of the battery. This will make this metal plate
positively charged. Similarly, at the negative end, the plate will
start to accumulate negative charges. This happens because the
electrons are repelled by the negative end of the battery. At some
point, the process reaches a kind of equilibrium, whereby the
electrons in the positively charged plate are attracted equally to the
plate as they are to the positive end of the battery, and thus stop
flowing. It is interesting to note that both plates of the capacitor
end up with the same total charge but different signs (i.e. =-q= and
=+q=).

We mentioned a "maximum limit". Two things control this limit: how big
the plates are and how much space there is between them. The bigger
they are and the closer they are - without touching - the more you can
store in the capacitor. The material used for the plates is, of
course, of great importance too - it must be some kind of metal good
at conducting.

In a more technical language, this is called the /capacitance/ and it
is given by the following formula:

: C = q / V

Lets break it down to its components to see what this formula is
telling us. We have a potential difference between the two plates
- because one is positively charged whereas the other one is negatively
charged, so you can imagine that a charge will have a different
electric potential in each. =q= tells us about the magnitude of the
charges that we placed on the plates. Capacitance is then a measure of
how much electric charge one can store for a given potential
difference.

It may not be very obvious from this formula, but capacitance is
constant. That is to say, a given capacitor has a constant
capacitance, influenced by the properties described above. This
formula does not describe how "full" or "empty" the capacitor is over
time.

Capacitance is measured in SI units of Farads, denoted by the letter
 =F=. A farad is 1 coulomb over 1 volt:

: 1F = C / V

* The RC Circuit

The /RC circuit/, or resistor-capacitor circuit, has a source of
current with a resistor and a capacitor:

#+CAPTION: Source: Wikipedia, [[https://en.wikipedia.org/wiki/RC_circuit][RC circuit]]
https://upload.wikimedia.org/wikipedia/commons/a/a4/Discharging_capacitor.svg

The RC circuit is a parallel circuit.
