#+title: Nerd Food: Neurons for Computer Geeks - Part VI: LIF At Long Last!
#+options: date:nil toc:nil author:nil num:nil title:nil

Welcome to part VI of a multi-part series on modeling neurons. In [[http://mcraveiro.blogspot.co.uk/2015/09/nerd-food-neurons-for-computer-geeks_7.html][part
V]] we added just a bit more theory to link electricity with neurons,
and also tried to give a vague idea of how complex neurons
are. Looking back on that post, I cannot help but noticed I skipped
one bit that is important to LIF. Lets look at that first, and then
proceed to the model.

* Resting Potential and Action Potential

We have spoken [[http://mcraveiro.blogspot.co.uk/2015/09/nerd-food-neurons-for-computer-geeks_7.html][before]] about the [[https://en.wikipedia.org/wiki/Membrane_potential][membrane potential]] and about the
resting membrane potential, but we did so with so much hand-waving
that it requires revisiting. When we are talking about the /resting/
membrane potential we mean just that - the value for the membrane
potential when nothing is happening and the membrane is left to its
own devices. That is the magical -65mv we discussed before (with all
of the related explanations on how to interpret negative
voltages). However, time does not stand still and things happen:
active ion gates get opened and shut, ions move around and the cell
changes its membrane potential. When these changes result in a higher
voltage - such as moving to -60mv - we say a /depolarisation/ is
taking place. Conversely, when the voltage becomes more negative, we
say /hyperpolarisation/ is occurring.

With neurons, it may just happen that there is a short-lived but
"strong" burst of depolarisation followed by rapid
hyperpolarisation. This is called an /[[https://en.wikipedia.org/wiki/Action_potential][action potential]]/, and it is
also known by many other names such as "nerve impulses" or
"spikes". When you hear that "a neuron has fired" this means that an
action potential has just been emitted. If you record the neuron's
behaviour over time you will see a /spike train/ - a plot of the
voltage over time, clearly showing the spikes. Taking a fairly random
example:

#+CAPTION: Source: Wikipedia, [[https://en.wikipedia.org/wiki/Neural_oscillation][Neural oscillation]]
#+attr_html: :width 300px :height 300px
https://upload.wikimedia.org/wikipedia/commons/1/1b/Simulation_of_hrose_neuron.png

One way of picturing this is as a kind of "chain-reaction" whereby
something triggers the voltage of the neuron to rise, which triggers a
number of gates to open, which then trigger the voltage to rise and so
on, until some kind of magic voltage threshold is reached where the
inverse occurs: the gates that were causing the voltage to rise shut
and some other gates that cause the voltage to decrease open and so on
until we fall back down to the resting membrane potential. In the case
of the picture above, something else triggers us again and again,
until we finally come to rest.

* Historical Background for the Integrate-and-Fire Model

A couple of years after Einstein's /annus mirabilis/, a french chap
called Lapicque was also having his moment of inspiration, with his
/[[http://www.snv.jussieu.fr/brette/papers/Lap07.pdf][Recherches quantitatives sur l'excitation électrique des nerfs
traitée comme une polarisation]]/, summarised [[http://neurotheory.columbia.edu/~larry/AbbottBrResBul99.pdf][here]] in accessible
terms.

Lapicque had the insight of thinking of the neuron as an RC circuit,
with the cell membrane's behaviour modeled as the interplay between
the capacitor and the resistor; the action potential we described
above was generated by the capacitor reaching a threshold and then
discharging. Even with our lack of understanding on the subject
matter, one cannot but appreciate Lapique's brilliance - having the
ability to reach these conclusions in 1907.

As it happens, this is still considered a useful model today, even
though we know so much more about neurons now. It is a great example
of what we mentioned [[http://mcraveiro.blogspot.co.uk/2015/09/nerd-food-neurons-for-computer-geeks_7.html][before]] in terms of modeling, in that each model
is designed for a specific purpose and it should be as simple as
possible for the stated end. Lapique's model still serves a purpose in
the world of today. It's worth [[http://neurotheory.columbia.edu/~larry/AbbottBrResBul99.pdf][reading Abbot]] in full here to ram the
point home:

#+begin_quote
While Lapicque, because of the limited knowledge of his time, had no
choice but to model the action potential in a simple manner, the
stereotypical character of action potentials allows us, even today, to
use the same approximation to avoid computation of the voltage
trajectory during an action potential.  This allows us to focus both
intellectual and computation resources on the issues likely to be most
relevant in neural computation, without expending time and energy on
modeling a phenomenon, the generation of action potentials, that is
already well understood.
#+end_quote

* The Leaky Integrate-and-Fire Model (LIF) Formula

LIF is defined as follows:

#+OPTIONS: tex:t
#+HTML_MATHJAX:  path:"http://cdn.mathjax.org/mathjax/latest/MathJax.js"
\begin{align}
\tau_m \frac{dv}{dt} = -v(t) + RI(t)
\end{align}

By now this should make vague sense, but lets do it step by
step. First we know that the current of the RC circuit is defined like
so:

#+OPTIONS: tex:t
#+HTML_MATHJAX:  path:"http://cdn.mathjax.org/mathjax/latest/MathJax.js"
\begin{align}
I(t) = I_R + I_C
\end{align}

From Ohm's Law we know that:

#+OPTIONS: tex:t
#+HTML_MATHJAX:  path:"http://cdn.mathjax.org/mathjax/latest/MathJax.js"
\begin{align}
I_R = \frac {v}{R}
\end{align}

And from the rigmarole of the capacitor we also know that:

#+OPTIONS: tex:t
#+HTML_MATHJAX:  path:"http://cdn.mathjax.org/mathjax/latest/MathJax.js"
\begin{align}
I_C = C \frac{dv}{dt}
\end{align}

Thus:

#+OPTIONS: tex:t
#+HTML_MATHJAX:  path:"http://cdn.mathjax.org/mathjax/latest/MathJax.js"
\begin{align}
I(t) = \frac {v(t)}{R} + C \frac{dv}{dt}
\end{align}

If we now multiply both sides by R:

#+OPTIONS: tex:t
#+HTML_MATHJAX:  path:"http://cdn.mathjax.org/mathjax/latest/MathJax.js"
\begin{align}
RI(t) = v(t) + RC \frac{dv}{dt}
\end{align}

Remember that RC is \tau, the RC time constant. In this case, it's for
the membrane so hence the /m/. The rest of the rearranging to the
original formula should hopefully be obvious.

If you recall, we mentioned [[https://en.wikipedia.org/wiki/Leaky_integrator][Leaky Integrators]] before; you should now
be able to see the resemblance with our first formula.

Note that we did not model spikes explicitly with this
formula. However, when it comes to implementing it, all that is
required is to look for a threshold value for the membrane potential -
called the /spiking threshold/; when that value is reached, we need to
reset the membrane potential back to a lower value - the /reset
potential/.

* Implementing the Formula

The first thing you cannot help but notice is that computers do not
know about calculus. This is a tad of a problem.

https://en.wikipedia.org/wiki/Euler_method

Neuroengineering Tutorial: Integrate and Fire neuron modeling
http://www.slideshare.net/ZubinBhuyan/x-neuro-integrate-and-fire-neuron-modeling

Integrate-and-fire model
http://icwww.epfl.ch/~gerstner/SPNM/node26.html

Leaky Integrate-and-Fire Model Neuron
http://people.brandeis.edu/~pmiller/COMP_NEURO/lifb.pdf
