#+title: Nerd Food: Neurons for Computer Geeks - Part III: More Electricity And More Morphology
#+options: date:nil toc:nil author:nil num:nil title:nil

[[http://mcraveiro.blogspot.co.uk/2015/08/nerd-food-neurons-for-computer-geeks.html][Part I]] of this series looked at a neuron from above; [[http://mcraveiro.blogspot.co.uk/2015/08/nerd-food-neurons-for-computer-geeks_31.html][Part II]] attempted
to give us the fundamental building blocks in electricity required to
get us on the road to modeling neurons. Regrettably, part III is
somewhat more of the same as part II: now that we grok the basics of
electricity, we need to turn our attention to the /RC circuit/. As we
shall see, this circuit is of particular interest when modeling
neurons. We will also try to fill in the gaps of part I to try to
converge to a slightly more realistic morphology of the neuron.

But back to the RC circuit. It is so called because it is a circuit,
and it is composed of a resistor and a capacitor. We've already got
some vague understanding of circuits and resistors, so lets have a
look at this new crazy critter, /the capacitor/.

* Capacitors

Just like the battery is a source of current, one can think of the
capacitor as a temporary store of current. If you plug a capacitor
into a circuit with just a battery, it will start to "accumulate"
charge over time, up to a "maximum limit". But how exactly does this
process work?

[[https://www.khanacademy.org/science/physics/circuits-topic/circuits-with-capacitors/v/capacitors-and-capacitance][In simple terms]], the capacitor is made up of two metal plates, one of
which will connect to the positive end of the battery and another
which connects to the negative end. At the positive end, the metal
plate will start to lose negative charges because these are attracted
to the positive end of the battery. This will make this metal plate
positively charged. Similarly, at the negative end, the plate will
start to accumulate negative charges. This happens because the
electrons are repelled by the negative end of the battery. Whilst this
process is taking place, the capacitor is _charging_.

At some point, the process reaches a kind of equilibrium, whereby the
electrons in the positively charged plate are attracted equally to the
plate as they are to the positive end of the battery, and thus stop
flowing. At this point we say the capacitor is _charged_. It is
interesting to note that both plates of the capacitor end up with the
same total charge but different signs (i.e. =-q= and =+q=).

** Capacitance

We mentioned a "maximum limit". A few things control this limit: how
big the plates are, how much space there is between them and the kind
of material we place between them, if any. The bigger the plates and
the closer they are - without touching - the more you can store in the
capacitor. The material used for the plates is, of course, of great
importance too - it must be some kind of metal good at conducting.

In a more technical language, this notion of a limit is captured by
the concept of /capacitance/, and is given by the following formula:

#+OPTIONS: tex:t
#+HTML_MATHJAX:  path:"http://cdn.mathjax.org/mathjax/latest/MathJax.js"
\begin{align}
C = \frac{q}{V}
\end{align}

Lets break it down to its components to see what the formula is trying
to tell us. The role of =V= is to inform us about the potential
difference between the two plates. This much is easy to grasp; since
one plate is positively charged and other negatively charged, it is
therefore straightforward to imagine that a charge will have a
different electric potential in each plate, and thus that there will
be an electric potential difference between them. =q= tells us about
the magnitude of the charges that we placed on the plates -
i.e. ignoring the sign. It wouldn't be to great a leap to conceive
that plates with a larger surface area would probably have more
"space" for charges and so a larger =q= - and vice-versa.

Capacitance is then the ratio between these two things; a measure of
how much electric charge one can store for a given potential
difference. It may not be very obvious from this formula, but
capacitance is constant. That is to say, a given capacitor has a
capacitance, influenced by the properties described above. This
formula does not describe the discharging or charging process - but of
course, capacitance is used in the formulas that describe those.

Capacitance is measured in SI units of Farads, denoted by the letter
 =F=. A farad is 1 coulomb over 1 volt:

#+OPTIONS: tex:t
#+HTML_MATHJAX:  path:"http://cdn.mathjax.org/mathjax/latest/MathJax.js"
\begin{align}
1F = \frac{C}{V}
\end{align}

** Capacitors and Current

After charging a capacitor, one may be tempted to discharge it. For
that one could construct a simple circuit with just the capacitor.
Once the circuit is closed, the negative charges will start to flow to
the positively charged plate, at full speed - minus the resistance of
the material. Soon enough both plates would be made neutral. At first
glance, this may appear to be very similar to our previous circuit
with a battery. However, there is one crucial difference: the battery
circuit had a constant voltage and a constant current (for a
theoretical battery) whereas a circuit with a discharging capacitor
has voltage and current that /decay/ over time. By "decaying", all we
really mean is that we start at some arbitrarily high value and we
move towards zero over a period of time. This makes intuitive sense:
you cannot discharge the capacitor forever, and as you discharge it
the voltage starts to decrease - for there are less charges in the
plates and so less potential difference - and similarly, so does the
current - for there is less "pressure" to make the charges flow.

This intuition is formally captured by the following equation:

#+OPTIONS: tex:t
#+HTML_MATHJAX:  path:"http://cdn.mathjax.org/mathjax/latest/MathJax.js"
\begin{align}
I(t) = C \frac{dV(t)}{dt}
\end{align}

I'm rather afraid that, at this juncture, we have no choice but to
introduce Calculus. A proper explanation of Calculus a tad outside the
remit of these posts, so instead we will have to make do with some
common-sense but extremely hand-waved interpretations of the ideas
behind it. If you are interested in a light-hearted but still
comprehensive treatment of the subject, perhaps [[http://betterexplained.com/articles/a-gentle-introduction-to-learning-calculus/][A Gentle Introduction
To Learning Calculus]] is more to your liking.

Let's start by taking a slightly different representation of the
formula above and then compare these two formulas.

#+OPTIONS: tex:t
#+HTML_MATHJAX:  path:"http://cdn.mathjax.org/mathjax/latest/MathJax.js"
\begin{align}
i = C \frac{dv}{dt}
\end{align}

In the first case we are talking about the current =I=, which normally
is some kind of average current over some unspecified period. Up to
now, /time/ didn't really matter - so we got away with just talking
about =I= in these general terms. This was the case with the resistors
in part II. However, as we've seen, it is not so with capacitors - so
we need to make the current specific to a point in time. For that we
supply an "argument" to I - =I(t)=; here, a mathematician would say
that that /=I= is a function of /time/. In the second case, we make
use of =i=, which is the /instantaneous current/ through the
capacitor. The idea is that, somehow, we are able to know - for any
point in time - what the instantaneous current is.

How we achieve that is via the magic of Calculus. The expression
=dv/dt= in the second formula provides us with the instantaneous rate
of change of the voltage over time. The same notion can be applied to
=V=, as per first formula.

These formulas may sound awfully complicated, but what they are trying
to tell us is that the capacitor's current has the following
properties:

- it varies as a "function" of time: =I(t)=; that is to say, different
  time points have different currents. Well, that's pretty consistent
  with our simplistic notion of a decaying current.
- it is "scaled" by the capacitor's capacitance =C=; "bigger"
  capacitors can hold on to higher currents for longer when compared
  to "smaller" capacitors.
- the change in electric potential difference varies as a function of
  time. This is subtle but also makes sense: we imagined some kind of
  decay for our voltage, but there was nothing to say the decay would
  remain /constant/ until we reached zero. This formula tells us it
  does not; voltage may decrease faster or slower at different points
  in time.

[[http://www.allaboutcircuits.com/textbook/direct-current/chpt-13/electric-fields-capacitance/][Electric Fields and Capacitance]]
[[http://www.allaboutcircuits.com/textbook/direct-current/chpt-13/capacitors-and-calculus/][Capacitors and Calculus]]

* The RC Circuit

The /RC circuit/, or resistor-capacitor circuit, has a source of
current with a resistor and a capacitor:

#+CAPTION: Source: Wikipedia, [[https://en.wikipedia.org/wiki/RC_circuit][RC circuit]]
https://upload.wikimedia.org/wikipedia/commons/a/a4/Discharging_capacitor.svg

The RC circuit is a parallel circuit.
